# Generated by Django 4.2.5 on 2025-03-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_letter', models.CharField(max_length=100, unique=True, verbose_name='тема')),
                ('body_letter', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['subject_letter', 'body_letter'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('comment', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['email', 'fullname'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sending', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('last_sending', models.DateTimeField(auto_now_add=True, verbose_name='Время конца')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('ended', 'Завершена')], default='created', editable=False, max_length=10, verbose_name='Статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_service.message', verbose_name='Сообщение')),
                ('recipient', models.ManyToManyField(related_name='mailings', to='mailing_service.recipient', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['first_sending', 'last_sending', 'status'],
            },
        ),
        migrations.CreateModel(
            name='AttemptMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('not success', 'Не успешно')], editable=False, max_length=11, verbose_name='Статус')),
                ('answer', models.TextField(editable=False, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing_service.mailing', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['date_attempt', 'status', 'answer', 'mailing'],
            },
        ),
    ]
