# Generated by Django 4.2.5 on 2025-03-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_alter_mailing_options_attemptmailing_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptmailing',
            name='owner',
        ),
    ]
